import Head from 'next/head';
import Link from 'next/link';
import { GetStaticPaths, GetStaticProps } from 'next';

const studies = {
  'womens-health': { title: "Women's Health Research Platform", type: 'Digital health research software', intro: "A longitudinal study platform designed around participant data collection and researcher review.", context: 'Developed during a summer research internship at IIT Ropar under Dr. Sujata Pal.', sections: [['Problem', 'Longitudinal health studies need consistent, structured data collection without making participant workflows unnecessarily difficult.'], ['Participant workflow', 'The system supports questionnaires, symptom and menstrual tracking, and repeat interactions across a study.'], ['Researcher workflow', 'Researcher-facing views support review of participant records and structured study data.'], ['Data architecture', 'A React and TypeScript client communicates with a Node.js and Express API backed by MongoDB, with JWT-based access control.'], ['Wearable integration', 'The platform includes workflows for bringing wearable data into the wider study record.'], ['What I built', 'I developed the research platform across participant and researcher experiences, backend APIs, data models, and authentication.'], ['Research direction', 'The system is intended as practical infrastructure for longitudinal digital-health research.']], github: 'https://github.com/cherikakaushal/women_health_research_platform' },
  'stress-management': { title: 'Stress Management Research Platform', type: 'Digital health research software', intro: 'A structured platform for stress-management studies, participant sessions, and physiological data.', context: 'Developed as one of two independent research platforms during a summer research internship at IIT Ropar.', sections: [['Problem', 'Stress studies need a reliable way to coordinate sessions, assessments, participant data, and researcher oversight.'], ['Participant workflow', 'Participants move through structured research sessions and stress-assessment workflows.'], ['Researcher workflow', 'Researcher dashboards support study oversight and review of collected information.'], ['Data architecture', 'The full-stack system uses React, TypeScript, Node.js, Express, MongoDB, REST APIs, and JWT authentication.'], ['Wearable integration', 'Physiological and wearable data can be associated with study sessions for later research review.'], ['What I built', 'I developed participant workflows, researcher-facing interfaces, backend services, and the study data layer.'], ['Research direction', 'The platform provides reusable software infrastructure for structured stress-management research.']] },
  'grubox': { title: 'Grubox Production Website', type: 'Production web development', intro: 'A production-site migration from Wix to Next.js, followed by ongoing feature and content development.', context: 'Delivered as part of software development and marketing work for Grubox.', sections: [['Problem', 'The existing Wix site needed to move to a code-based platform that could support continued product and content development.'], ['Migration to Next.js', 'The website was rebuilt on Next.js, translating the existing presence into a maintainable production codebase.'], ['What I implemented', 'My work spans frontend development, content implementation, feature updates, and the continuing evolution of the website.'], ['Website architecture', 'Next.js provides the foundation for reusable pages and components while supporting production deployment.'], ['Ongoing maintenance', 'The work continues beyond the initial migration through site updates, content changes, and feature development.']] },
  'buildvr': { title: 'BuildVR Multilingual Landing Pages', type: 'Web · 3D/VR', intro: 'Multilingual web experiences developed alongside immersive 3D/VR product work.', context: 'Selected work from a software development and marketing internship at BuildVR.', sections: [['Context', 'BuildVR creates immersive digital experiences for audiences with different language and content needs.'], ['Landing-page work', 'I developed web landing pages that communicate the product clearly to distinct audiences.'], ['Multilingual adaptation', 'Pages were adapted for multiple languages and markets while maintaining a consistent experience.'], ['3D/VR work', 'The broader role includes work with immersive applications, 3D assets, and AI-assisted video workflows.'], ['Technical implementation', 'My contributions span implementation, content integration, testing, and deployment.']] },
} as const;

type Slug = keyof typeof studies;
export const getStaticPaths: GetStaticPaths = async () => ({ paths: Object.keys(studies).map(slug => ({ params: { slug } })), fallback: false });
export const getStaticProps: GetStaticProps = async ({ params }) => ({ props: { slug: params?.slug } });
export default function Work({ slug }: { slug: Slug }) { const study = studies[slug]; return <><Head><title>{study.title} · Cherika Kaushal</title><meta name="description" content={study.intro} /></Head><div className="case-page ds-theme-dark"><nav className="case-nav"><Link href="/">CK.</Link><Link href="/#projects">← All work</Link></nav><main><header className="case-hero"><span>{study.type}</span><h1>{study.title}</h1><p>{study.intro}</p></header><section className="case-context"><span>Context</span><p>{study.context}</p></section><div className="case-sections">{study.sections.map(([title, copy], i) => <section key={title}><span>{String(i + 1).padStart(2,'0')}</span><div><h2>{title}</h2><p>{copy}</p></div></section>)}</div>{'github' in study && <a className="case-cta" href={study.github} target="_blank" rel="noreferrer">View repository ↗</a>}</main><footer className="case-footer"><span>Cherika Kaushal · Research & Software</span><Link href="/#contact">Contact →</Link></footer></div></> }
